### ISSUE TITLE
不是哥们，你确定你这个代码是对的？

### ISSUE THREAD

**Issue by qinziming** [PengyaoYi/zeroRumor_AAAI#13]
1. 首先，你这里面`torch.stack`的时候都没检查是否为空列表，一开始跑就根本跑不通
![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/113889031/130497b9-8d6d-4314-84c1-82ae5096333e)
2. 其次，跑你的代码不停地有`cuda out of memory`的问题，我给加到四张V100都不行，严重怀疑你这个结果是怎么出来的
![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/113889031/271d57da-f44b-4196-9940-695bbb3d32c9)
3. 希望得到你尽快的回复

**Comment by PengyaoYi** [comment]
1. the  embeds for torch.stack func have been construct into 0/1 pairs strictly  in the dataloader part. And the last batch data is also  droped from input. 
2. the model batch size is set to 16 which is a relatively small num. Besides，our dataloader part code doesn't modify for multi card training. So I wonder how you can run this code with 4 GPUs parallelly? And I think problem 1 is related to this.
3. Kind words go a long way

**Comment by Deno-V** [comment]
遇到了类似的问题。
实验条件：3090 （24G）4卡 / 采用和作者描述的完全一致的环境运行run.py脚本，所以可以排出环境问题导致的错误
实验观察：代码运行后会自动吃4张卡的显存，并且和楼主一样碰上torch.stack报错，具体来说就是embeds这个list有一个元素会是空列表。
观察1：如果强行指定CUDA_VISIBLE_DEVICES为单卡，那么将会CUDAOOM
观察2:  在四卡运行时debug观察了每张卡上batch的label情况，发现每张卡上都只有label=0或者label=1的样本，这就是导致embeds这个list中有空元素的真正原因

猜想：上面回复中作者说他没有实现多卡训练逻辑，从代码上来看也确实如此，但实际上却是代码吃了4张卡（原因未知）。作者本意应该是一个batch中label为0或者1的数量是成对的，但实际上观察到是每张卡都仅有一种label的样本导致了error。
解决方案：屏蔽了作者trainer.py脚本中所有和ddp/parallel等相关的内容，并且把batchsize降低到8后，程序可以正常执行训练。
建议：个人感觉代码仍然存在问题，应该出在多卡问题上，不知作者是否有检查可能导致该方面的原因？虽然当前勉强运行起来了，但依旧觉得不踏实，有劳。

Experiment Conditions: Using 4 GPUs (3090, 24GB each) with an environment that is identical to what the author described in the run.py script, so we can rule out environmental issues causing the error.

Observations:

After running the code, it automatically consumes the memory of all 4 GPUs. Like the user in the forum, I encountered a torch.stack error, specifically because the embeds list contains an empty list as one of its elements.
Observation 1: If I forcefully specify CUDA_VISIBLE_DEVICES to a single GPU, it results in a CUDA out-of-memory (OOM) error.
Observation 2: When running on four GPUs and debugging, I checked the batch labels on each GPU and found that each GPU only has samples with either label 0 or label 1, which is the real reason behind the empty element in the embeds list.
Hypothesis: The author mentioned they did not implement multi-GPU training logic, and based on the code, it indeed seems so. However, it appears that the code is still utilizing all 4 GPUs (the reason for this is unknown). The author's intention seems to be that the number of samples with label 0 and label 1 in each batch should be paired, but the actual observation indicates that each GPU only has samples of one label, leading to the error.

Solution: I commented out all the parts related to DDP/parallel in the author's trainer.py script and reduced the batch size to 8. After that, the program was able to execute the training properly.

Suggestion: I personally feel the code still has issues, likely related to multi-GPU handling. I'm not sure if the author has examined potential causes for this aspect. Although it runs somewhat smoothly now, I still feel uncertain about its reliability.
